name: Run Gradle Task

jobs:
  integration-test:
    name: Integration Tests
    runs-on: self-hosted
    steps:
      # setup build environment
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.6
