name: Run Gradle Task

jobs:
  integration-test:
    name: Integration Tests
    runs-on: self-hosted
    steps:
      # setup build environment
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
